FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements-full.txt /app/requirements-full.txt
RUN pip install --no-cache-dir -r /app/requirements-full.txt

COPY backend/ /app/backend/
WORKDIR /app/backend
ENV PYTHONPATH=/app/backend

EXPOSE 8000
CMD ["uvicorn","app.api_app:app","--host","0.0.0.0","--port","8000","--ws-ping-interval","25","--ws-ping-timeout","40"]
