FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements-full.txt /app/requirements-full.txt
RUN pip install --no-cache-dir -r /app/requirements-full.txt

COPY backend/ /app/backend/
WORKDIR /app/backend
ENV PYTHONPATH=/app/backend

CMD ["python","main.py"]
